### ISSUE TITLE
Incompatibility with protocol buffer 3.0.0a4

### ISSUE THREAD

**Issue by leconteur** [ethereon/caffe-tensorflow#10]
I updated tensorflow, which updated protocol buffer to version 3.0.0a4. I can't import any model anymore. 

To reproduce the bug, go in the caffe-tensorflow/caffe folder, and execute the following code:

    python
    Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from google import protobuf
    >>> protobuf.__version__
    '3.0.0a4'
    >>> import caffepb
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "caffepb.py", line 28, in <module>
            type=None),
      File "/Users/olivier/pythonvenv/tf/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 652, in __new__
        _message.Message._CheckCalledFromGeneratedFile()
    TypeError: Descriptors should not be created directly, but only retrieved from their parent.
    >>> exit()

**Comment by ethereon** [comment]
Seems to be working fine for me:
```
Python 2.7.10 (default, Sep 23 2015, 04:34:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import protobuf
>>> protobuf.__version__
'3.0.0a4'
>>> import caffepb
>>>
```

**Comment by leconteur** [comment]
Sorry, seems like I had two versions of protocol buffer installed at the same time.

**Comment by devashishshankar** [comment]
Hi, I'm getting the exact same issue. I did a fresh install of tensorflow.
@leconteur how did you fix this?

Thanks!

**Comment by leconteur** [comment]
I did a couple of permutations of de-installing and reinstalling everything in various order. I can't remember the correct order.

**Comment by jeandut** [comment]
Same issue here would appreciate if you could expand @leconteur .

**Comment by leconteur** [comment]
I never found out exactly what was the problem. I end up installing from scratch in a new virtualenv if I break my installation. Sorry.

**Comment by jeandut** [comment]
Ok tks for answering anyway ! : )

**Comment by shuangwu** [comment]
I have the same issue, protobuf 3.2.0, the following helped.
pip install protobuf==3.0.0

**Comment by HugoFeng** [comment]
Got the same issue, but @shuangwu 's approach doesn't solve mine... @jeandut have you find a way? Thank you!

**Comment by HugoFeng** [comment]
~~I find this [link](https://dev.gajim.org/gajim/gajim/issues/8458)  and after I downgraded protobuf this error disappeared~~
using an older version of protobuf will somehow lead to [this](https://github.com/tensorflow/tensorflow/issues/5168) error... I'm stuck again..

**Comment by yuanming-hu** [comment]
In the same situation as @HugoFeng ... I tried `protobuf` 3.2.0, 3.0.0, 2.6.1 and unfortunately none of them works. I can not import `caffepb` with 3.2.0 or 3.0.0, while 2.6.1 will cause the tensorflow error (1.0.0rc2).

**Comment by kyu-sz** [comment]
Renaming any file creating descriptors to have suffix "_pb2.py" will solve this problem. See PR #105 .
