### ISSUE TITLE
How to handle MemoryData layers

### ISSUE THREAD

**Issue by zachrattner** [ethereon/caffe-tensorflow#11]
I'm trying to convert a GoogLeNet with a `MemoryData` layer as the first layer: 

    layer {
      name: "googlenet"
      type: "MemoryData"
      top: "data"
      top: "label"
      memory_data_param {
        batch_size: 32
        channels: 3
        height: 224
        width: 224
      }
    }

When I run `convert.py`, I run into the `shape_identity` issue: 

    # We most likely have a data layer on our hands. The problem is,
    # Caffe infers the dimensions of the data from the source (eg: LMDB).
    # We want to avoid reading datasets here. Fail for now.
    # This can be temporarily fixed by transforming the data layer to
    # Caffe's "input" layer (as is usually used in the "deploy" version).
    # TODO: Find a better solution for this.

What does it mean to transform the data layer to an input layer? Can you provide more information on how to do this? Thanks.

**Comment by ethereon** [comment]
I just pushed an update which adds support for memory data layers, so everything should correctly now.
