### ISSUE TITLE
question on google protobuf...

### ISSUE THREAD

**Issue by amiltonwong** [ethereon/caffe-tensorflow#115]
Hi, all.

I got the following error when I execute the following command:

(tf_1.0) root@milton-All-Series:~/caffe-tensorflow/examples/mnist# python ../../convert.py lenet.prototxt --code-output-path=mynet.py

```
 File "/root/anaconda3/envs/tf_1.0/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 824, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: expected bytes, str found

```

It seems the version of my google protobuf may not match this package, which version protobuf are you using? (In my machine, the version is  3.2.0  for google protobuf)

THX!

**Comment by amiltonwong** [comment]
I figure it out. This package should be used in python 2.7.x environment. Furthermore, environment under google protobuf>=3.2.0 should be tackled according to [this thread](https://github.com/ethereon/caffe-tensorflow/pull/105)

**Comment by sslx** [comment]
@amiltonwong, would you mind elaborating on this?
"To solve this, the file creating descriptors must be named with suffix "_pb2.py"."
Which file do I need to rename to make caffe-tensorflow to work?
protobuf=3.11.2
Thanks!
