### ISSUE TITLE
Multiple .prototxt files

### ISSUE THREAD

**Issue by tengerye** [ethereon/caffe-tensorflow#151]
I have never used Caffe before. I want to convert [this model] https://github.com/ddtm/caffe/tree/grl/models/bvlc_alexnet) to TensorFlow. However, I found three .prototxt files under that folder. Namely, they are deploy.prototxt, solver.prototxt, and train_val.prototxt.

Then I tried to convert only one file followed by this error.
"Error encountered: Multiple top nodes are not supported."

How could I add those three files as input please?
Thank you in advance.

**Comment by brothertook** [comment]
I suppose you should use deploy.prototxt as network structure  file and bvlc_alexnet.caffemodel for weights (http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel).

**Comment by tengerye** [comment]
Thank you very much. My problem has been solved.
