### ISSUE TITLE
The accuracy of converted AlexNet weights is not as high as description.

### ISSUE THREAD

**Issue by zh0ngtian** [ethereon/caffe-tensorflow#154]
I download the `npy` file from [here](http://www.cs.toronto.edu/%7Eguerzhoy/tf_alexnet/). It was converted using caffe-tensorflow. I tested it on ILSVRC2012_val dataset, but I only got 48% top 1 accuracy and 73% top 5 accuracy.

**Comment by PaulZhangIsing** [comment]
Similar situation encountered here. I converted self defined net and the accuracy drops from about 80% to 13.2%
