### ISSUE TITLE
Converting to protobuf?

### ISSUE THREAD

**Issue by zachrattner** [ethereon/caffe-tensorflow#16]
The inception net in the [Android Tensorflow Demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) stores the model as a protobuf file ([tensorflow_inception_graph.pb](https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip)). Is it possible to convert the python scripts outputted to protobuf format?

**Comment by ethereon** [comment]
Sure. You can use TensorFlow's [saving API](https://www.tensorflow.org/versions/0.6.0/api_docs/python/state_ops.html#Saver) from within a session to create the model protobuf file.

**Comment by zachrattner** [comment]
Thanks, setting this up, but what do I put for the data argument since I have a pre-trained Caffe model and not the training images? Your tool outputs mynet.py and mynet.npy, and I'm trying to use the saving API by adding this to the bottom of mynet.py: 

```
if __name__ == "__main__":
  net = MyNet({'data': 'some-data-here'}) # not sure what to give for data?
  with tf.Session() as sess:
    net.load('mynet.npy', sess)
    saver = tf.train.Saver()
    saver.save(sess, 'mynet-out', global_step=1000)
```

**Comment by ethereon** [comment]
You can use a [placeholder](https://www.tensorflow.org/versions/0.6.0/api_docs/python/io_ops.html#placeholders) for the data. For instance, [here's how the test script does it](https://github.com/ethereon/caffe-tensorflow/blob/master/test.py#L52).
