### ISSUE TITLE
Issue Converting AlexNet

### ISSUE THREAD

**Issue by zplizzi** [ethereon/caffe-tensorflow#18]
I have what I imagine is a rather simple problem. I'm trying to import the standard bvlc_alexnet model from the Caffe github (caffe/models/bvlc_alexnet). I've tried both the train_val and the solver prototext file, and get different errors for each - both in the first layer. 

In train_val.prototext, the first layer is:
```
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: true
    crop_size: 227
    mean_file: "data/ilsvrc12/imagenet_mean.binaryproto"
  }
  data_param {
    source: "examples/imagenet/ilsvrc12_train_lmdb"
    batch_size: 256
    backend: LMDB
  }
}
```
and the error is "Cannot determine the dimensions of data layer".
If I use deploy.prototext:
```
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 10 dim: 3 dim: 227 dim: 227 } }
}
```
I get an error because the "Input" layer is not recognized, and also because the "input_param" property is not recognized. 

I'm sure I'm doing something foolish, but can't seem to figure it out! Perhaps including a sample prototext file that converts successfully would help people like me massage our files into the correct format?

**Comment by osimeoni** [comment]
+1

Isn't those errors yield by Tensorflow new version (0.7) ?

**Comment by ethereon** [comment]
This is due to a recent [Caffe change](https://github.com/BVLC/caffe/commit/00598ca84e2611cf3bbd363d4920796ce1517ff2) that added the `Input` layer type. This results in two issues with Caffe-Tensorflow:

1. If you're using the fallback protobuf backend, it's outdated and will not recognize this layer. However, the PyCaffe backend should work fine.

2.  The `Input` layer type won't be detected by the caffe-tensorflow mapper.

While the fixes are relatively straightforward, it'll probably be a few days before I get time to make the changes. In the meantime, the older version of AlexNet's `deploy.txt` should work fine.

**Comment by dpfau** [comment]
I'm having the same issue - is there a quick workaround until a fix gets pushed?

**Comment by zplizzi** [comment]
@ethereon great, thanks - this makes sense.

@dpfau the workarounds mentioned (using PyCaffe backend, or using an older `deploy.txt` (probably found in Github file history)) should work fine (although I haven't tested yet).

**Comment by dpfau** [comment]
I don't think that will work - I already had to update my deploy.prototxt since it was too old. Is there some kind of goldilocks deploy.prototxt that's neither too recent nor too old?

**Comment by zplizzi** [comment]
Yep - [this one](https://github.com/BVLC/caffe/blob/2f5889cb84b8c7f8f64a6b7eb48e1dc624b18162/models/bvlc_alexnet/deploy.prototxt) worked for me.

**Comment by ethereon** [comment]
I just pushed a new version that should resolve these issues.

**Comment by dpfau** [comment]
Just realized I wasn't clear on which network I was trying to convert - I was having these issues with VGG, not AlexNet. In any case, I pulled the update and it works now. Thanks!
