### ISSUE TITLE
Can you provide numpy blobs

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [ethereon/caffe-tensorflow#2]
Can you provide numpy blobs, so that it can be used without Caffe?
Also I am trying to convert VGG-Face net from lua code, it should have similar structure like this?

**Comment by ethereon** [comment]
The version I just pushed no longer depends on Caffe.
I'm not familiar with VGG-Face, but I'd assume the process would be fairly similar.

**Comment by AKSHAYUBHAT** [comment]
I have already processed vgg face using the torch version. Thanks
