### ISSUE TITLE
Is an installed Caffe a must when using convert.py?

### ISSUE THREAD

**Issue by yangta1995** [ethereon/caffe-tensorflow#22]
I tried to convert caffe model 'VGG_CNN_M' to fine-tune in Tensorflow. However, an error occurred:
'Unknown layer type encountered:4'
Do I need to install Caffe first, or how come is the error.
Thanks!

**Comment by ethereon** [comment]
Is the model in the latest format? If not, please upgrade it as described in the readme first.
