### ISSUE TITLE
Why there always should input prototxt and caffemodel together into convert.py ?

### ISSUE THREAD

**Issue by ZhuFengdaaa** [ethereon/caffe-tensorflow#25]
Because I only want to get the tensorflow prototext. 

I want to train the tensorflow prototext under the tensorflow framework, but `convert.py` tells me I should pass the caffemodel into it. I'm wondering if there can be the way input the caffe prototxt without caffemodel and get the tensorflow code only.

**Comment by ethereon** [comment]
Fixed in #26. You should be able to convert just the model definition without the .caffemodel file now.
