### ISSUE TITLE
Need variant batch size and image size

### ISSUE THREAD

**Issue by kuanfang** [ethereon/caffe-tensorflow#29]
One of the current limits seems to be that you cannot use variant batch size or image size in the network. This is caused by the reshape and get_shape functions in the Network class. Because you need to set the 1st dimension of the placeholder of input batch data to be None to use variant batch size, and set the 2nd and 3rd dimensions to be None to use variant image size.

In what cases do we need to reshape the output like [this](https://github.com/ethereon/caffe-tensorflow/blob/master/kaffe/tensorflow/network.py#L93-95)? I found it is not necessary at least for alexNet. If not, I can do some changes and make a push.

**Comment by ethereon** [comment]
The old `network.py` was long due for an update. You're right: the reshape is no longer necessary.

The current version no longer has this limitation and should work just fine with variable batch sizes.
