### ISSUE TITLE
TensorFlow-Slim

### ISSUE THREAD

**Issue by mmuneebs** [ethereon/caffe-tensorflow#32]
Tensorflow has a new higher level abstraction similar to Lasagne (for Theano) now. It would be great if the conversion to tensorflow can use this new format to make the models much more neat/slim.
[https://github.com/tensorflow/models/tree/master/inception/inception/slim](url)

**Comment by ethereon** [comment]
Using a higher-level library like TensorFlow-Slim could definitely make things a bit cleaner. However, there are a few reasons I'd like to avoid it (at least for now):
- It would introduce a new dependency (of course, on the other hand, it could be an optional thing)
- The current wrapper (`network.py`) deals with some of the idiosyncrasies of Caffe/TensorFlow. Something equivalent would still be required.

Besides these, the auto-generated code is limited by Caffe's source prototxt. In many cases (eg: GoogLeNet), a hand-written version compatible with the converted weights would be much cleaner than any auto-gen version.

**Comment by mmuneebs** [comment]
Yes, and as of now, TF-Slim hasn't been merged with tensorflow/contrib main repo.
