### ISSUE TITLE
Reshape layer is unknown...

### ISSUE THREAD

**Issue by san-bil** [ethereon/caffe-tensorflow#34]
So given a network that reshapes some dense activations to a set of a feature maps, convert.py throws out:

Error encountered: Unknown layer type encountered: Reshape

Can support for reshape be added easily?

**Comment by ethereon** [comment]
Yeah, reshape support should be straight forward. If you want to take a shot at it, here's a rough outline:

- Add an entry for the reshape layer to `LAYER_DESCRIPTORS` in `layers.py` and a corresponding function in `shape.py` (that basically returns the new shape)
- Add a `map_reshape` to `TensorFlowMapper` in `tensorflow/transformer.py`
- Add the mapped function to `network.py` that calls `tf.reshape`

You'll need to make sure that the reshaped dimensions are properly mapped from Caffe's NCHW to TensorFlow's NHWC ordering

**Comment by pribadihcr** [comment]
Hi @san-bil,

Did you have implement the reshape layer ?

**Comment by javierrodenas** [comment]
Hi, 

Have you solved the problem?
