### ISSUE TITLE
Get variables values

### ISSUE THREAD

**Issue by omidb** [ethereon/caffe-tensorflow#37]
Hi, 

thanks for the library. Is there a way to get the value of a specific layer? for example if I want to get feature vectors like fc7 or fc8, how should I get the values of these variables?
Or is it possible to run the model not to the end? for example have forward path just for first 4 layers?

Thanks

**Comment by ethereon** [comment]
@omidb Sure - you can simply evaluate the operation corresponding to the layer you're interested in, rather than the terminal node.
