### ISSUE TITLE
Error encountered: Unknown layer type encountered: 4 for VGG-16 laycer CNN

### ISSUE THREAD

**Issue by StephenBydawell** [ethereon/caffe-tensorflow#39]
Using the command: ./convert.py VGG_ILSVRC_16_layers_deploy.prototxt --code-output-path=mynet.py

.prototxt obtained from: https://gist.github.com/ksimonyan/211839e770f7b538e2d8

**Comment by SepehrV** [comment]
The problem is with the version of Caffe that your prototxt file is written for.
In more recent versions of Caffe, some syntax for prototxt files has changed. E.g. layers changed to layer or now the type of layers is a string. 
So to solve the issue you can simply modify the prototxt file so that it would be compatible with latest release of Caffe. 

To do so, apply these changes:
```
layers -> layer
CONVOLUTION -> "Convolution"
POOLING -> "Pooling"
RELU -> "ReLU"
INNER_PRODUCT -> "InnerProduct"
SOFTMAX -> "Softmax"
DROPOUT -> "Dropout"
LRN -> "LRN"
```

**Comment by StephenBydawell** [comment]
Thanks for your response. I implemented the changes and now have this error:

xt_format.py", line 764, in ConsumeIdentifier
    raise self._ParseError('Expected identifier.')
google.protobuf.text_format.ParseError: 1:1 : Expected identifier.

I changed the attached .prototxt to .txt
[VGG_ILSVRC_16_layers_deploy.txt](https://github.com/ethereon/caffe-tensorflow/files/313521/VGG_ILSVRC_16_layers_deploy.txt)


Your assistance is much appreciated.

**Comment by ethereon** [comment]
I'd recommend using the `upgrade_net_proto_text` and `upgrade_net_proto_binary` tools bundled with Caffe for updating the `.prototxt` and `.caffemodel` files respectively, as described in the readme.

**Comment by StephenBydawell** [comment]
Managed to get a new .prototxt. Thanks for the help.

**Comment by Yaffa1607** [comment]
Hi , I do not have caffe , I was wondering if someone can upgrade a prototxt file and share?
I'm trying to convert this caffe model to tensprflow. http://vision.soic.indiana.edu/egohands_files/hand_classifier.prototxt

**Comment by Serhiy-Shekhovtsov** [comment]
@Yaffa1607 have you ever got the `hand_classifier.prototxt` converted?

**Comment by geoffzhang** [comment]
Hi, @SepehrV , Do you have the problem of "Error encountered: Unknown layer type encountered: Normalize", can you give me some advice, please?

**Comment by sumaira-hussain** [comment]
Hi 
I am using same command to convert my caffe model into tensorflow. I have updated my both prototxt and caffemodel files. but still I am getting this error.
![image](https://user-images.githubusercontent.com/23133444/50136317-64db6b80-02d2-11e9-84d0-ff0cee5fefbf.png)

can anybody tell what is wrong?
