### ISSUE TITLE
types of the layers are all in numbers, not string (e.g, Convolution, LRN)

### ISSUE THREAD

**Issue by jazzsaxmafia** [ethereon/caffe-tensorflow#4]
Hi, thank you for making public this project.
I was trying to run convert.py to get TensorFlow version of VGG16 model, but it raises a weird error.

The problem seems like, the value of layer.type is always in number (4: Convolution, 18: something else...), rather than the string like "Convolution" or "Pooling" (line #200 in kaffe/core.py). 

I am not sure if I am doing something wrong...
Could you please help me get over this?

Thank you
-Taeksoo

**Comment by ethereon** [comment]
It sounds like you're using the old Caffe format (the original VGG16 gist uses the old format as well).

Try upgrading the prototxt and caffemodel to the most current version, as described in the readme.

**Comment by jazzsaxmafia** [comment]
Thank you for quick response, I will try that.

**Comment by jazzsaxmafia** [comment]
It worked like magic. Thank you!
