### ISSUE TITLE
the conv5_4/weights does not exist

### ISSUE THREAD

**Issue by kecaiwu** [ethereon/caffe-tensorflow#41]
I have convert the vgg-16 and vgg-19 caffemodel to tensorflow model, but i get one error about using the tensorflow model classify the image. vgg-16 get the conv5_1/weights does not exist, and vgg-19 get the conv5_4/weights does not exist. can you give me some advice?

![2016-06-22_103014](https://cloud.githubusercontent.com/assets/17605639/16252873/6323ccc8-3864-11e6-8cc5-6eb5ffb9a443.png)

**Comment by ethereon** [comment]
I just checked VGG16, and everything seems to be working correctly. If you're using the `classify.py` script included in the examples, make sure you've replaced the `GoogleNet` instances with `VGG16` (on lines 32 and 39)

**Comment by kecaiwu** [comment]
I have test the googlenet instead of the vgg16 or vgg19, the googlenet is working well, thx.
