### ISSUE TITLE
Error encountered: Multiple top nodes are not supported.

### ISSUE THREAD

**Issue by ceykmc** [ethereon/caffe-tensorflow#42]
I tried to convert caffe's bvlc_googlenet, using the following script:
`./convert.py CAFFE_ROOT_PATH/models/bvlc_googlenet/train_val.prototxt --code-output-path ./bvlc_googlenet.py`
Then I got:
`Error encountered: Multiple top nodes are not supported.`
I am using the latest caffe version.
Where was i doing wrong? Thanks in advance.

**Comment by fartashf** [comment]
You should try deploy.prototxt. Current version has difficulty with the way
data and label is fed into the network in train_val.prototxt

**Comment by ceykmc** [comment]
It works well when using deploy.prototxt.
Thanks for replying, and this convenient tool !!
