### ISSUE TITLE
Test on large dataset

### ISSUE THREAD

**Issue by lbg940131** [ethereon/caffe-tensorflow#43]
When I run classify.py and test on GoogleNet, the result is not as expected.
When I tested on a dataset with more than 2000 images, it only gives me 200(the batch size) classification results.

**Comment by ethereon** [comment]
The `classify.py` example is intended for small batches of images. The maximum number is capped at the model batch size (200 for GoogLeNet/Inception). I'd recommend checking out `validate.py`, which runs on arbitrarily large datasets.
