### ISSUE TITLE
possible problem with SoftmaxWithLoss

### ISSUE THREAD

**Issue by Shalily** [ethereon/caffe-tensorflow#45]
I'm trying to convert a NIN model and post conversion while saving source i get this error:
"Error encountered: No handler found for node kind: SoftmaxWithLoss (expected: map_softmax_with_loss)"
Is that a problem with the SoftmaxWithLoss support or is this a problem with my specific model?
thanks
S.R.H

**Comment by ethereon** [comment]
Currently, caffe-tensorflow primarily supports inference-mode conversions.
Conversion for many of the "training layers", including SoftmaxWithLoss, has not been implemented.
Taking out the SoftmaxWithLoss layer, or using the "deploy" version, should work
