### ISSUE TITLE
Weight Normalization

### ISSUE THREAD

**Issue by antonilo** [ethereon/caffe-tensorflow#46]
Usually during training add a normalization to the weights used in CNN is a good way to improve the generalization performance. 
If I did not misread the code, at the moment it seems that it is not trivial to get the weights during learning. 
It seems to me that it might be a good idea to store also the weights in the Network class for easy retrieval during learning.

**Comment by ethereon** [comment]
The weights and biases are stored in regular tensorflow variables (see the `load` function for instance). You can access these just like any other tensorflow variables (which you can also use for adding regularization). For more details, [see here](https://www.tensorflow.org/versions/r0.10/api_docs/python/state_ops.html#get_variable).
