### ISSUE TITLE
weights data format

### ISSUE THREAD

**Issue by DannyGal** [ethereon/caffe-tensorflow#47]
I used caffe-tensorflow to convert Caffe Alex network.
The convolution weights data format isn't as expected.

Convolution Node data_format value is 'NHWC' (default)
But the weights node data format was HWCN, 
Looking at the "Shape" attribute values I found that it also formatted as HWCN .
For example, for conv1 layer
- expected W=11,H=11, C=3, N=96
- shape dim is {11,11,3,96}

I expected it to be {96,11,11,3} - NHWC

On the other hand, the above format matches the python convert code (network.py - line 123)

`kernel = self.make_var('weights', shape=[k_h, k_w, c_i / group, c_o])`

why does the converter script use this data format (HWCN) ?

**Comment by ethereon** [comment]
I believe you're confusing the shape for the input tensor, which is expected to be `(N=batch_size, H=height, W=width, C=channels)`, with the shape for the convolution parameters, which is expected to be `(H=kernel_height, W=kernel_width, C_in=channels_in, C_out=channels_out)`. 

More details here: https://www.tensorflow.org/versions/r0.9/api_docs/python/nn.html#conv2d
