### ISSUE TITLE
Error importing caffe after running convert.py

### ISSUE THREAD

**Issue by JulianBlin** [ethereon/caffe-tensorflow#56]
Hi,
I'm using this on AWS to convert a handtuned caffe model to tensorflow. CUDA is installed, Caffe also with Python support. Tensorflow also.

The problem is very strange : at the first time I launch python, I can `import caffe` succesfully. But after, I try to run `convert.py`, it fails and I'm not able to import caffe anymore in any python command line.

Logs : 

> ubuntu@ip:~$ `python`
> Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > `import caffe`
> > > > `import tensorflow`
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
> > > > `print tensorflow.__version__`
> > > > 0.10.0rc0
> > > > ubuntu@ip:~/tensorflow/caffe-tensorflow$ `python convert.py ../../caffe-master/models/deploy.prototxt --caffemodel ../../caffe-master/models/imagenet_train_iter_5000.caffemodel  --data-output-path output/`
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
> > > > I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
> ---
> 
> ```
> WARNING: PyCaffe not found!
> Falling back to a pure protocol buffer implementation.
> * Conversions will be drastically slower.
> * This backend is UNTESTED!
> ```
> ---
> 
> Error encountered: Unknown layer type encountered: 4
> ubuntu@ip:~/tensorflow/caffe-tensorflow$ `python`
> Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > `import caffe`
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > > ImportError: No module named caffe

**Comment by swearos** [comment]
can you find caffe folder in '/usr/local/lib/python2.7/dist-packages',you need copy the caffe folder to the python package folder

**Comment by zt706** [comment]
To import the caffe Python module after completing the installation, add the module directory to your $PYTHONPATH by export PYTHONPATH=/path/to/caffe/python:$PYTHONPATH or the like.
