### ISSUE TITLE
ValueError on vgg_face model

### ISSUE THREAD

**Issue by junhocho** [ethereon/caffe-tensorflow#6]
![image](https://cloud.githubusercontent.com/assets/15857111/11428639/de97549a-94b0-11e5-9e65-09697bc479de.png)

 Hi, thanks for providing this code. I am having issue on changing caffemodel of vgg_face provided from http://www.robots.ox.ac.uk/~vgg/software/vgg_face/ and having above error.

 I changed the old caffe format to new caffe format (layers --> layer) with your README hint.
 But having valueerror.

Thank you very much.

**Comment by ethereon** [comment]
Tested on VGG face: works fine for me. Could you please try with the latest version of the code I just pushed?
Also, please verify that the Caffe version that you used to upgrade the prototxt/caffemodel files is a fairly recent one.

**Comment by ethereon** [comment]
Assuming this has been resolved. If not, feel free to open another issue.

**Comment by ethereon** [comment]
Update: this issue occurred when PyCaffe was not found and the fallback parser was used. This has now been fixed.
