### ISSUE TITLE
how can i save the transformed model graph ?

### ISSUE THREAD

**Issue by yossibiton** [ethereon/caffe-tensorflow#60]
I managed to convert my caffe model successfully into 2 files (python class and npy weights file).
Now i want to save the converted model as ordinary tensorflow graph.

this is an example for the desired graph file format :
[http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz -o /tmp/inceptionv3.tgz](http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz -o /tmp/inceptionv3.tgz)

**Comment by yossibiton** [comment]
let's say the conversion script generated these 2 files :
1.  python class is named MyNet
2. weights file names 'mynet.npy'

Then, running these lines will save the serialized graph in protobuf format :

`data_node = tf.placeholder(tf.float32, shape=(None, 224, 224, 3))`
`net = MyNet({'data': data_node})`
`sess = tf.Session()`
`net.load(data_path='mynet.npy', session=sess)`
`f = tf.gfile.FastGFile(model_dir+'mynet.pb', "w")`
`f.write(output_graph.as_graph_def().SerializeToString())`
`f.close()`

**Comment by tmatas** [comment]
Hi,
in your snippet `output_graph` is not defined. 
How can you get it from `f` or from `net`?

Thank you

**Comment by yossibiton** [comment]
sess.graph()

**Comment by tmatas** [comment]
Thank you! I think this snippet works
```
data_node = tf.placeholder(tf.float32, shape=(None, 224, 224, 3))
net = MyNet({'data': data_node})
with tf.Session() as sess:
    output_graph = sess._graph
    net.load(data_path='mynet.npy', session=sess)
    f = tf.gfile.FastGFile(model_dir+'mynet.pb', "w")
    f.write(output_graph.as_graph_def().SerializeToString())
    f.close()
```

**Comment by tmatas** [comment]
If this might help, when I run `classify.py` over [this image](http://www.l-arcadinoe.com/it/wp-content/uploads/2011/06/mare.jpg) I get this output on the console:


```
Loading the model
E tensorflow/core/client/tensor_c_api.cc:485] FIFOQueue '_0_path_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: path_queue_Dequeue = QueueDequeue[_class=["loc:@path_queue"], component_types=[DT_INT32, DT_BOOL, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](path_queue)]]
Loading the images
Classifying

Image                Classified As                  Confidence
----------------------------------------------------------------------
mare.jpg             coral reef                     89.69 %
```

**Comment by shrutisharmavsco** [comment]
@tmatas are you looking to populate the data from your .npy file into the tensorflow model (.pb file)? If yes, this might be what you're looking to do: https://github.com/ethereon/caffe-tensorflow/issues/23
