### ISSUE TITLE
layer.type returns number instead of string

### ISSUE THREAD

**Issue by joker512** [ethereon/caffe-tensorflow#67]
Hello,

In kaffe/graph.py:

```
def make_node(self, layer):
    '''Create a graph node for the giver layer.'''
    kind = NodeKind.map_raw_kind(layer.type)
    if kind is None:
        raise KaffeError('Unknown layer type encountered: %s' % layer.type)
...
```
layer.type returns number instead of layer name.

As a consequence:

`./convert.py --caffemodel model.caffemodel --data-output-path build --code-output-path build deploy.prototxt`

fails with:

`Error encountered: Unknown layer type encountered: 4`
For the first CONVOLUTION layer in deploy.prototxt.

Can anyone help? It seems that protobuf do something wrong. I have 3.0.2 version on my PC.

**Comment by fbiswt** [comment]
Did you solve this problem ? I have a same one

**Comment by joker512** [comment]
No, I didn't. :(

**Comment by fbiswt** [comment]
I solved this problem by update the caffe model.
But I have a new problem that Flatten layer is not implemented

**Comment by joker512** [comment]
What do you mean by "update the caffe model"? Did you rebuild .caffemodel binary with the latest build of caffe?

**Comment by ethereon** [comment]
@joker512 Please see the note about upgrading in the readme. There are also multiple closed issues on this topic.
