### ISSUE TITLE
Wrong layer names about GoogleNet maybe

### ISSUE THREAD

**Issue by carsonDB** [ethereon/caffe-tensorflow#69]
When I read your specification of googlenet layers, I found
some of layers' names of GoogleNet are wrong, as I can understand.
Here is an [example](https://github.com/ethereon/caffe-tensorflow/blob/master/examples/imagenet/models/googlenet.py#L9).
Maybe it should be called "conv2_1x1_reduce".

**Comment by ethereon** [comment]
The names are automatically copied from the source: https://github.com/BVLC/caffe/blob/master/models/bvlc_googlenet/train_val.prototxt#L100

The Caffe model, in turn, bases it on the original paper from Google, which says: 
>  "3×3 reduce" and "5×5 reduce" stands for the number of 1×1 filters in the reduction layer used before the 3×3 and 5×5 convolutions

source: https://arxiv.org/pdf/1409.4842v1.pdf (page 6)

**Comment by carsonDB** [comment]
Thank you very much for patient and detailed answer.
