### ISSUE TITLE
Memory errors?

### ISSUE THREAD

**Issue by jmhessel** [ethereon/caffe-tensorflow#9]
When I use your program on vgg16, I am having memory problems. Conversion works (after upgrading files), and I am able to reconstruct the graph in memory. However, when I attempt to do a forward-pass with a batch size of 32 images, I run out of memory. The error happens after "initialization" of variables. However, to my knowledge, tf.initialize_all_variables() doesn't actually initialize anything -- the next time you run something, initialization is triggered; so it makes sense why the error doesn't occur when I am constructing the graph in memory.

The out of memory error happens when I attempt to run something in a session. Within the first few convolutional layers of VGG16 is generally when things run out of memory. For instance, when I run it on a GTX 980 (4GB of ram) my GPU runs out of memory  and in around the 3rd convolutional layer when I run it on a GTX Titian X (12GB of ram). Do you have any thoughts about why this might be the case? I am using the most recent caffe + tensorflow.

Here's the bash script im using to preprocess. Directly following this I am loading into tensorflow. I am running your scripts from inside another repository, so there might be slight differences.

Anyt thoughts?
   
    #/bin/bash
    
    CAFFE_PATH=~/caffe

    wget http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel
    wget https://gist.githubusercontent.com/ksimonyan/211839e770f7b538e2d8/raw/0067c9b32f60362c74f4c445a080beed06b07eb3/VGG_ILSVRC_16_layers_deploy.prototxt

    $CAFFE_PATH/build/tools/upgrade_net_proto_text VGG_ILSVRC_16_layers_deploy.prototxt tmp.prototxt
    mv tmp.prototxt VGG_ILSVRC_16_layers_deploy.prototxt

    $CAFFE_PATH/build/tools/upgrade_net_proto_binary VGG_ILSVRC_16_layers.caffemodel tmp.caffemodel
    mv tmp.caffemodel VGG_ILSVRC_16_layers.caffemodel

    ./caffe-tensorflow/convert.py VGG_ILSVRC_16_layers_deploy.prototxt VGG_ILSVRC_16_layers.caffemodel vgg.npy vgg.py
    echo "import sys
    sys.path.append('caffe-tensorflow')
    " | cat - vgg.py > tmp.py

    mv tmp.py vgg.py
    rm VGG_ILSVRC_16_layers.caffemodel VGG_ILSVRC_16_layers_deploy.prototxt

**Comment by ethereon** [comment]
VGG16 is notoriously memory-hungry. I usually use a batch-size of at most 25 on a 12GB Titan X.

You can find the batch sizes I used for various architectures [over here](https://github.com/ethereon/caffe-tensorflow/blob/master/examples/__init__.py).

**Comment by jmhessel** [comment]
Got it -- thanks for the heads up, I didn't know that VGG was particularly memory hungry, but I know now. Thanks! :)
